version: "3.8"
services:
  db:
    image: "postgres:12"
    container_name: "blog_db"
    ports:
      - $DB_PORT:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
